apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: suraj
  labels:
    project: suraj
    env: dev
    component: db

  
spec:
  replicas: 3
  selector:
    matchLabels:
      proejct: suraj
      env: dev
      component: db

  template:
    metadata:
      labels:
        project: suraj
        env: dev
        component: db

    spec:
      containers:
      - name: user
        image: 296062550816.dkr.ecr.us-east-1.amazonaws.com/suraj/dev/user:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user

---


apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: suraj

spec:
  selector:
    project: suraj
    env: dev
    component: db

  ports:
  - name: user-port
    protocol: TCP
    port: 8080
    targetPort: 8080

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: suraj

data:
  MONGO: "true"
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/users"